# Generated by Django 4.1.4 on 2023-04-16 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modify_at', models.DateField(auto_now=True)),
                ('on_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('on_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modify_at', models.DateTimeField(auto_now=True)),
                ('on_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MenuModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(editable=False, max_length=15)),
                ('number', models.PositiveSmallIntegerField(default=50)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modify_at', models.DateField(auto_now=True)),
                ('on_deleted', models.BooleanField(default=False)),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.food')),
            ],
        ),
    ]
