# Generated by Django 4.1.4 on 2023-04-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='available_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
