# Generated by Django 4.1.4 on 2023-04-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_menumodel_available_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menumodel',
            name='available_time',
        ),
    ]
