# Generated by Django 4.1.4 on 2023-05-08 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0022_alter_usermodel_package_alter_usermodel_rank'),
        ('admin_panel', '0003_remove_menumodel_available_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Rank',
        ),
    ]
