# Generated by Django 4.1.4 on 2023-04-16 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_panel', '0004_alter_usermodel_options_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='craeted_at',
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
