# Generated by Django 4.1.4 on 2023-04-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0005_remove_cart_craeted_at_alter_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='modify_at',
        ),
    ]
