# Generated by Django 4.1.4 on 2023-04-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0008_cart_modify_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='modify_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
