# Generated by Django 4.1.4 on 2023-04-17 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('user_panel', '0015_usermodel_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_panel.package'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='admin_panel.rank'),
        ),
    ]
