# Generated by Django 4.1.4 on 2023-04-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0016_usermodel_package_usermodel_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='inventory',
            field=models.IntegerField(default=0),
        ),
    ]
