# Generated by Django 4.1.4 on 2023-04-17 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0017_usermodel_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='on_delete',
            new_name='on_deleted',
        ),
    ]
