# Generated by Django 4.1.4 on 2023-04-19 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0019_remove_usermodel_inventory_wallet_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='on_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
