# Generated by Django 4.1.4 on 2023-05-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_panel', '0022_alter_usermodel_package_alter_usermodel_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.IntegerField(max_length=9999999, unique=True),
        ),
    ]
