# Generated by Django 4.1.4 on 2023-05-10 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_delete_package_delete_rank'),
        ('user_panel', '0029_payment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='admin_panel.menumodel'),
        ),
    ]
